### ISSUE TITLE
Video of the talk

### ISSUE THREAD

**Issue by ww9** [pwaller/go2ll-talk#1]
Is there a video of this talk?

Would love to watch it.

**Comment by pwaller** [comment]
Nice to know there is lots of interest! Apologies, there was no recording. I'll be publishing the full go2ll at some point. In the meantime there are several other LLVM-based go compilers in existence:

* https://github.com/go-llvm/llgo
* https://go.googlesource.com/gollvm/
* https://tinygo.org/

Also if you want to get involved, there is a [channel](https://gophers.slack.com/messages/CGF3TU056/) on the [gophers slack](https://gophersinvite.herokuapp.com/).

**Comment by advancedwebdeveloper** [comment]
> Nice to know there is lots of interest! Apologies, there was no recording. I'll be publishing the full go2ll at some point. In the meantime there are several other LLVM-based go compilers in existence:
> 

>~~ * https://github.com/go-llvm/llgo ~~
This one is a dead project

> * https://go.googlesource.com/gollvm/
This one is alive one, for sure

> * https://tinygo.org/
This one is supported, too

> 
> Also if you want to get involved, there is a [channel](https://gophers.slack.com/messages/CGF3TU056/) on the [gophers slack](https://gophersinvite.herokuapp.com/).

Already joined.

I am sharing gollvm's builds, from time to time.
